<?php

/**
 * @file
 * Module file for Webform Views Select.
 */

/**
 * Implements hook_views_api().
 */
function webform_views_select_views_api() {
  return array(
    'api' => 3,
  );
}

/**
 * Implements hook_webform_select_options_info().
 */
function webform_views_select_webform_select_options_info() {
  $views = views_get_enabled_views();
  $items = array();

  foreach ($views as $view) {
    if (!empty($view->display)) {
      foreach ($view->display as $id => $display) {
        if ($view->display[$id]->display_plugin == 'webform_select') {
          if (!empty($view->human_name)) {
            $viewname = $view->human_name;
          }
          else {
            $viewname = $view->name;
          }
          $items[$view->name . '-' . $id] = array(
            'title' => t('Views') . ': ' . $viewname . ' - ' . $display->display_title,
            'options callback' => 'webform_views_select_options',
            'options arguments' => array('view' => $view->name, 'display_id' => $id),
          );
        }
      }
    }
  }

  return $items;
}

/**
 * Callback for retrieving webform select options.
 *
 * @see webform_options_example()
 */
function webform_views_select_options($component, $flat, $filter, $args = array()) {
  // In Webform 4.x, $filter has been removed and the value $args is really the
  // third parameter. This means that when $args is empty, we need to get the
  // arguments from the $filter argument.
  if (empty($args)) {
    $args = $filter;
  }

  // Get the view and execute it.
  $view = views_get_view($args['view']);
  $view->set_display($args['display_id']);

  return webform_views_select_options_from_view($view, $flat);
}

/**
 * Internal function to get the results.
 */
function webform_views_select_options_from_view($view, $flat = FALSE) {
  $view->pre_execute();
  $view->render();

  // Check if the view was built correctly.
  if (!$view->built) {
    watchdog('webform_views_select', 'There was an error while building display %display of view %view', array('%view' => $view->name, '%display' => $view->current_display), WATCHDOG_ERROR);
    return array();
  }

  return $view->display_handler->execute($flat);
}
